// Generated by derive-wizard

#set page(
  paper: "a4",
  margin: (x: 2.5cm, y: 2cm),
)

#set text(font: "Liberation Serif", size: 11pt)
#set par(justify: false, leading: 0.5em, spacing: 0.5em)
#show heading: set text(weight: "bold")

#align(center)[
  #text(size: 16pt, weight: "bold")[Job Application]
]

#text(size: 10pt, style: "italic")[Please complete this job application form.]

#block(spacing: 0.4em)[
  #grid(
    columns: (auto, 1fr),
    column-gutter: 0.6em,
    align: (left + horizon, left + horizon),
    text(size: 10pt)[Full name:],
    box(
      width: 100%,
      height: 1.5em,
      stroke: (bottom: 0.5pt + black),
      inset: (x: 2pt, bottom: 1pt),
    )[]
  )
]

#block(spacing: 0.4em)[
  #grid(
    columns: (auto, 1fr),
    column-gutter: 0.6em,
    align: (left + horizon, left + horizon),
    text(size: 10pt)[Email address:],
    box(
      width: 100%,
      height: 1.5em,
      stroke: (bottom: 0.5pt + black),
      inset: (x: 2pt, bottom: 1pt),
    )[]
  )
]

#block(spacing: 0.4em)[
  #text(size: 10pt)[Select variant:]
  #v(0.15em)
  #grid(
    columns: (auto, 1fr),
    gutter: 0.4em,
    align: (left + horizon, left + horizon),
    box(
      width: 1.2em,
      height: 1.2em,
      stroke: 0.5pt + black,
    )[],
    text(size: 10pt)[Developer]
  )
  #v(0.2em)
  #grid(
    columns: (auto, 1fr),
    gutter: 0.4em,
    align: (left + horizon, left + horizon),
    box(
      width: 1.2em,
      height: 1.2em,
      stroke: 0.5pt + black,
    )[],
    text(size: 10pt)[Designer]
  )
  #v(0.2em)
  #grid(
    columns: (auto, 1fr),
    gutter: 0.4em,
    align: (left + horizon, left + horizon),
    box(
      width: 1.2em,
      height: 1.2em,
      stroke: 0.5pt + black,
    )[],
    text(size: 10pt)[Manager]
  )
]

#block(spacing: 0.4em)[
  #text(size: 10pt)[Technical skills (select all that apply):]
  #v(0.15em)
  #grid(
    columns: (auto, 1fr),
    gutter: 0.4em,
    align: (left + horizon, left + horizon),
    box(
      width: 1.2em,
      height: 1.2em,
      stroke: 0.5pt + black,
    )[],
    text(size: 10pt)[Rust]
  )
  #v(0.2em)
  #grid(
    columns: (auto, 1fr),
    gutter: 0.4em,
    align: (left + horizon, left + horizon),
    box(
      width: 1.2em,
      height: 1.2em,
      stroke: 0.5pt + black,
    )[],
    text(size: 10pt)[Python]
  )
  #v(0.2em)
  #grid(
    columns: (auto, 1fr),
    gutter: 0.4em,
    align: (left + horizon, left + horizon),
    box(
      width: 1.2em,
      height: 1.2em,
      stroke: 0.5pt + black,
    )[],
    text(size: 10pt)[JavaScript]
  )
  #v(0.2em)
  #grid(
    columns: (auto, 1fr),
    gutter: 0.4em,
    align: (left + horizon, left + horizon),
    box(
      width: 1.2em,
      height: 1.2em,
      stroke: 0.5pt + black,
    )[],
    text(size: 10pt)[Go]
  )
  #v(0.2em)
  #grid(
    columns: (auto, 1fr),
    gutter: 0.4em,
    align: (left + horizon, left + horizon),
    box(
      width: 1.2em,
      height: 1.2em,
      stroke: 0.5pt + black,
    )[],
    text(size: 10pt)[SQL]
  )
]

#block(spacing: 0.4em)[
  #text(size: 10pt)[Available times:]
  #v(0.15em)
  #grid(
    columns: (auto, 1fr),
    gutter: 0.4em,
    align: (left + horizon, left + horizon),
    box(
      width: 1.2em,
      height: 1.2em,
      stroke: 0.5pt + black,
    )[],
    text(size: 10pt)[Morning]
  )
  #v(0.2em)
  #grid(
    columns: (auto, 1fr),
    gutter: 0.4em,
    align: (left + horizon, left + horizon),
    box(
      width: 1.2em,
      height: 1.2em,
      stroke: 0.5pt + black,
    )[],
    text(size: 10pt)[Afternoon]
  )
  #v(0.2em)
  #grid(
    columns: (auto, 1fr),
    gutter: 0.4em,
    align: (left + horizon, left + horizon),
    box(
      width: 1.2em,
      height: 1.2em,
      stroke: 0.5pt + black,
    )[],
    text(size: 10pt)[Evening]
  )
  #v(0.2em)
  #grid(
    columns: (auto, 1fr),
    gutter: 0.4em,
    align: (left + horizon, left + horizon),
    box(
      width: 1.2em,
      height: 1.2em,
      stroke: 0.5pt + black,
    )[],
    text(size: 10pt)[Weekends]
  )
]

#block(spacing: 0.4em)[
  #text(size: 10pt)[Open to remote work?]
  #v(0.15em)
  #grid(
    columns: (auto, auto, 1.5em, auto, auto),
    gutter: 0.4em,
    align: horizon,
    box(width: 1.2em, height: 1.2em, stroke: 0.5pt + black)[],
    text(size: 10pt)[Yes],
    [],
    box(width: 1.2em, height: 1.2em, stroke: 0.5pt + black)[],
    text(size: 10pt)[No],
  )
]


